version: '3.9'
services:
  user:
    image: flav1ann/msuser:latest
    hostname: user
    depends_on:
      - registration
      - docker-mysql
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar -Dspring.profiles.active=prod msUser.jar"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8083:8083
    environment:
      - secret_token=hvs.fQCDPLZuAGIfuxGFb2xbxSaU
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS=registration:8761
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  school:
    image: flav1ann/msschool:latest
    hostname: school
    depends_on:
      - registration
      - docker-mysql
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar -Dspring.profiles.active=prod msSchool.jar"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8084:8084
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS=registration:8761
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  configuration:
    image: flav1ann/msconfig:latest
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - secret_token=hvs.fQCDPLZuAGIfuxGFb2xbxSaU
    ports:
      - 8888:8888
    networks:
      - app-network
  gateway:
    image: flav1ann/msgateway:latest
    hostname: gateway
    depends_on:
      - registration
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar -Dspring.profiles.active=prod msGateway.jar"
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8099:8099
    environment:
      - secret_token=hvs.fQCDPLZuAGIfuxGFb2xbxSaU
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS=registration:8761
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  registration:
    image: flav1ann/msregistry:latest
    depends_on:
      - configuration
    command: sh -c "/wait && java -server -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -jar -Dspring.profiles.active=prod MsRegistry.jar"
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registration:8761/eureka
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  angular:
    image: flav1ann/angular_compte:latest
    depends_on:
      - registration
    command: sh -c "/wait && nginx -g 'daemon off;'"
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 83:80
    environment:
      - WAIT_HOSTS=user:8083
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
  docker-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: root
     entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS school; ' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: overlay
    internal: true
    attachable: true
