FROM maven:3.8.4-openjdk-11-slim as build
RUN mkdir msUser
WORKDIR /msUser
COPY ./ ./
RUN mvn clean package spring-boot:repackage
RUN ls
RUN ls ./target

FROM adoptopenjdk/openjdk11:alpine-jre
COPY --from=build /msUser/target/*.jar /jar-files/msUser.jar
WORKDIR /jar-files
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait


EXPOSE 8083
CMD ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-jar","-Dspring.profiles.active=prod", "msUser.jar"]